# Generated by Django 4.1.2 on 2024-04-17 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('stuname', models.TextField(max_length=50)),
                ('stuemail', models.EmailField(max_length=40)),
                ('stupass', models.IntegerField()),
            ],
        ),
    ]
