# Generated by Django 5.0.1 on 2024-04-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datastudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuname', models.CharField(max_length=30)),
                ('sturoll', models.IntegerField()),
                ('stucollege', models.CharField(max_length=60)),
                ('stucourse', models.CharField(max_length=30)),
                ('stuaddress', models.CharField(max_length=40)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
