# Generated by Django 4.1.2 on 2024-04-18 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuid', models.IntegerField()),
                ('stuname', models.CharField(max_length=40)),
                ('stufathername', models.CharField(max_length=50)),
                ('stumothername', models.CharField(max_length=50)),
                ('mobileno', models.IntegerField(max_length=10)),
            ],
        ),
    ]
